site_name: The Human Colossus Foundation
site_url: https://the-human-colossus-foundation.github.io/oca-spec/
site_author: The Human Colossus Foundation
site_description: >-
  Overlays Capture Architecture Specification


repo_name: oca-spec
repo_url: https://github.com/the-human-colossus-foundation/oca-spec
docs_dir: "spec"
site_dir: "html"


copyright: >-
  Copyright &copy; 2020 The Human Colossus Foundation


nav:
  - Overlays Capture Architecture: index.md


theme:
  name: material
  custom_dir: theme/overrides
  features:
    - navigation.instant
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  palette:
    primary: white
    accent: indigo

# Plugin configuration
plugins:
  - search

# Extensions configuration
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: trustoverip
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Additional content
extra:
  title: 'Overlays Capture Architecture'
  hcf_url: https://humancolossus.foundation
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/the-human-colossus-foundation
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/humancolossus
